ALTER TABLE Event
ADD NextRoundDate DATETIME NULL;

ALTER TABLE Event
ADD NextRoundTrack NVARCHAR NULL;

ALTER TABLE Event
ADD NextTrackMessageId NVARCHAR(100) NULL;

ALTER TABLE Event
ADD StandingsMessageId NVARCHAR(100) NULL;

ALTER TABLE Event
ADD TwitterMessage NVARCHAR(280) NULL;
