name: Docker on Tag

on:
  push:
    tags:
      - '[0-9].[0-9]+'
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: alex9158/ttbot
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: ${{ secrets.AZURE_SSH_KNOWN_HOSTS }}
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          name: id_rsa
          if_key_exists: replace        
      -
        name: Deploy Image
        run: ssh alex@52.151.89.75 'sudo docker pull alex9158/ttbot:latest && sudo docker stop ttbot && sudo docker rm ttbot && sudo docker run -v=/data/ttbot:/data/ttbot --name=ttbot --env-file /data/ttbot/.env -itd alex9158/ttbot:latest'
      
