name: Docker Image CI

on:
  push:
    branches: [ release ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: alex9158/ttbot:latest
      -
        name: Install SSH Key
        uses: shimatoro/ssh-key-action@v2
        with:
          known_hosts: ${{ secrets.AZURE_SSH_KNOWN_HOSTS }}
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          name: id_rsa
          if_key_exists: replace        
      -
        name: Deploy Image
        run: ssh alex@52.151.89.75 'sudo docker pull alex9158/ttbot:latest && sudo docker stop ttbot && sudo docker rm ttbot && sudo docker run -v=/data/ttbot:/data/ttbot --name=ttbot --env-file /data/ttbot/.env -itd alex9158/ttbot:latest'
      
